# Documentation: https://starship.rs/config/

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
${custom.hostname}\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$python\
$ruby\
$line_break\
$status\
$character"""

[character]
success_symbol = "[\uf4b5](fg:#58C09F) "
error_symbol = "[\uf4b5](bold fg:#EC7432) "

[directory]
truncation_length = 3
fish_style_pwd_dir_length = 1
format = "[$read_only]($read_only_style)[$path]($style) "
style = "bold fg:blue"
read_only = "\uea75 "
read_only_style = "fg:#F69F37"
truncation_symbol = "…/"

[git_branch]
symbol = "\uf418 "
style = "bold fg:#F05032"

[git_commit]
only_detached = false
tag_disabled = false
tag_symbol = "\uf02b "

[git_status]
stashed = "\uf487"
style = "bold fg:yellow"

[python]
symbol = "\ue73c "
style = "bold fg:#3776AB"

[ruby]
symbol = "\ue739 "
style = "bold fg:#CC342D"

[username]
style_user = "bold fg:#F5C643"
show_always = true
aliases = { "carlos.alvaro" = "Carlos", "cdalvaro" = "Carlos" }

[custom.hostname]
description = 'Custom hostname delegated to salt deployment'
when = true
symbol = "{{ pillar.config.starship.hostname_symbol }}"
style = "bold fg:{{ pillar.config.starship.hostname_color }}"
format = "[$symbol {{ pretty_hostname }}]($style) in "
