# Documentation: https://starship.rs/config/

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
${custom.macOS_hostname}\
${custom.linux_hostname}\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$python\
$ruby\
$line_break\
$status\
$character"""

[character]
success_symbol = "[􀆔](fg:#58C09F) "
error_symbol = "[􀆔](bold fg:#EC7432) "

[directory]
truncation_length = 3
fish_style_pwd_dir_length = 1
format = "[$read_only]($read_only_style)[$path]($style) "
style = "bold fg:blue"
read_only = "􀎡 "
read_only_style = "fg:#F69F37"
truncation_symbol = "…/"

[git_branch]
symbol = "\uf418 "
style = "bold fg:#F05032"

[git_commit]
only_detached = false
tag_disabled = false
tag_symbol = "\uf02b "

[git_status]
stashed = "\uf487"
style = "bold fg:yellow"

[python]
symbol = "\ue73c "
style = "bold fg:#3776AB"

[ruby]
symbol = "\ue739 "
style = "bold fg:#CC342D"

[username]
style_user = "bold fg:#F5C643"
show_always = true
aliases = { "carlos.alvaro" = "Carlos", "cdalvaro" = "Carlos" }

[custom.macOS_hostname]
description = "Show the model name of the Mac"
command = "/usr/local/sbin/starship-mac-model"
# Posible cmd: system_profiler -json SPHardwareDataType | jq '.SPHardwareDataType[0].machine_name'
os = "macos"
symbol = "{{ pillar.config.starship.hostname_icon }}"
style = "bold fg:{{ pillar.config.starship.hostname_color }}"
format = "[$output]($style) in "
when = true

[custom.linux_hostname]
description = "Show the hostname of the Linux machine"
command = "hostnamectl --pretty"
os = "linux"
symbol = "{{ pillar.config.starship.hostname_icon }}"
style = "bold fg:{{ pillar.config.starship.hostname_color }}"
format = "[$symbol($output)]($style) in "
when = true
