# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
${custom.mac_model}\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$cmake\
$python\
$ruby\
$swift\
$line_break\
$status\
$character"""

[character]
success_symbol = "[􀆔](fg:#58C09F) "
error_symbol = "[􀆔](bold fg:#EC7432) "

[directory]
truncation_length = 3
fish_style_pwd_dir_length = 1
format = "[$read_only]($read_only_style)[$path]($style) "
style = "bold fg:blue"
read_only = "􀎡 "
read_only_style = "fg:#F69F37"
truncation_symbol = "…/"

[git_branch]
symbol = "\uf418 "
style = "bold fg:#F05032"

[git_commit]
only_detached = false
tag_disabled = false
tag_symbol = "\uf02b "

[git_status]
stashed = "\uf487"
style = "bold fg:yellow"

[python]
symbol = "\ue73c "
style = "bold fg:#3776AB"

[ruby]
symbol = "\ue739 "
style = "bold fg:#CC342D"

[swift]
symbol = "\ue755 "
style = "bold fg:#FA7343"

[username]
style_user = "bold fg:#F5C643"
show_always = true
aliases = { "carlos.alvaro" = "Carlos", "cdalvaro" = "Carlos" }

[custom.mac_model]
description = "Show the model of the Mac"
command = "/usr/local/sbin/starship-mac-model"
os = "macos"
style = "bold fg:#CDCED0"
format = "[$output]($style) in "
when = true
