format = """
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$cmake\
$python\
$swift\
$memory_usage\
$custom\
$line_break\
$jobs\
$status\
$character"""

[character]
success_symbol = "[􀦱](bold fg:#999999) "
error_symbol = "[􀦮](bold fg:#AC1B2E) "

[directory]
truncation_length = 3
fish_style_pwd_dir_length = 1
format = "[$read_only]($read_only_style)[$path]($style) "
style = "bold fg:#00AAD1"
read_only = "􀎡 "
read_only_style = "fg:#EE8738"
truncation_symbol = "…/"

[git_branch]
symbol = "\uf418 "
style = "bold fg:#F05032"

[git_commit]
symbol = "\uf02b "
tag_disabled = false

[git_status]
stashed = "\uf487"
style = "bold fg:#FCA121"

[python]
symbol = "\ue73c "
style = "bold fg:#3776AB"

[swift]
symbol = "\ue755 "
style = "bold fg:#FA7343"
