#!/usr/bin/env zsh

# Custom gpg command to sign commits from IDEs such as Xcode, Visual Studio Code
# https://gist.github.com/cdalvaro/f136792780e4306887daed3d9a64e972
/usr/local/bin/gpg --batch --pinentry-mode=loopback --passphrase-file ~/.gnupg/key.txt --no-tty "$@"
