[colors]
ansi = [
  "#f8f4f2",
  "#cf5275",
  "#4d9a6d",
  "#c07d2d",
  "#d1673f",
  "#6c58b7",
  "#4289a4",
  "#282429",
]
background = "#f8f4f2"
brights = [
  "#a39fa0",
  "#cf5275",
  "#4d9a6d",
  "#c07d2d",
  "#d1673f",
  "#6c58b7",
  "#4289a4",
  "#282429",
]
cursor_bg = "#6f6b6d"
cursor_border = "#6f6b6d"
cursor_fg = "#6f6b6d"
foreground = "#282429"
selection_bg = "#bdb9ba"
selection_fg = "#282429"

# [colors.indexed]
# 16 = "#e8bbd0"
# 17 = "#cdab53"
# 18 = "#3a3432"
# 19 = "#4a4543"
# 20 = "#807d7c"
# 21 = "#d6d5d4"

[metadata]
aliases = ["Monokai Pro Light"]
author = "Carlos Álvaro (http://github.com/cdalvaro)"
name = "Monokai Pro Light"
origin_url = "https://monokai.pro"
wezterm_version = "20220807-113146-c2fee766"
