[general]
live_config_reload = true

[window]
dimensions = { columns = 135, lines = 64 }
decorations_theme_variant = "Dark"
resize_increments = true
dynamic_padding = true
padding = { x = 5, y = 5 }

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 12.0

[cursor]
style = { shape = "Beam", blinking = "Always" }

[keyboard]
# https://github.com/alacritty/alacritty/wiki/Keyboard-mappings
bindings = [
  # Jump between words with Option key
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left", mods = "Alt", chars = "\u001BB" },
  # Delete whole line with cmd + backspace
  { key = "Back", mods = "Command", chars = "\u0015" },
  # Delete word with option + backspace
  { key = "Back", mods = "Alt", chars = "\u001B\u007F" },
  # Ctrl + C using cmd + .
  { key = ".", mods = "Command", chars = "\u0003" },
]

# Monokai Pro (Octagon)
[colors]
cursor = { text = "#b3b8bc", cursor = "#b3b8bc" }
selection = { text = "#ebf1f0", background = "#535661" }

[colors.primary]
background = "#282938"
foreground = "#ebf1f0"

[colors.normal]
black = "#282938"
red = "#ec6f7c"
green = "#bfd671"
yellow = "#f8d87d"
blue = "#f19f69"
magenta = "#bc9bc5"
cyan = "#a7cfbc"
white = "#ebf1f0"

[colors.bright]
black = "#696c76"
red = "#ec6f7c"
green = "#bfd671"
yellow = "#f8d87d"
blue = "#f19f69"
magenta = "#bc9bc5"
cyan = "#a7cfbc"
white = "#ebf1f0"

[colors.search]
matches = { foreground = "#282938", background = "#ffff00" }
focused_match = { foreground = "#ebf1f0", background = "#535661" }
