name: Deploy dotfiles

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy dotfiles
    runs-on: ubuntu-latest
    env:
      SALTAPI_URL: ${{ secrets.SALTAPI_URL }}
      SALTAPI_USER: ${{ secrets.SALTAPI_USER }}
      SALTAPI_PASS: ${{ secrets.SALTAPI_PASS }}
      SALTAPI_EAUTH: ${{ secrets.SALTAPI_EAUTH }}
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install salt-pepper
        run: |
          pip install salt-pepper
      - name: Update fileserver
        run: |
          pepper --client runner --output-file /dev/null fileserver.update
      - name: Apply states
        run: |
          pepper -C 'G@os:macOS and *.cdalvaro.io' state.apply formulas.cdalvaro.config.home,formulas.cdalvaro.applications.vim --return cdalvaro
